version: '3'

services:
  db_app:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ylab
    ports:
      - '127.0.0.1:6040:5432'

  redis_app:
    image: redis:latest
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
