version: '3.9'

services:
  db_test:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: test_postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_ylab
    ports:
      - '127.0.0.1:6050:5432'

  redis:
    image: redis:latest
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
