version: '3.9'

services:
  db_test:
    container_name: db_test
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: test_postgres
      POSTGRES_PASSWORD: test_postgres
      POSTGRES_DB: test_ylab
    ports:
      - '127.0.0.1:6050:5432'
    healthcheck:
      test: sh -c "pg_isready -U test_postgres -d test_ylab"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  test_redis:
    container_name: test_redis
    image: redis:latest
    restart: always
    ports:
      - '127.0.0.1:6479:6379'
    healthcheck:
      test: sh -c "redis-cli ping"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  test_rabbitmq:
    container_name: test_rabbitmq
    image: rabbitmq:3.13-alpine
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "127.0.0.1:5682:5672"
    networks:
      - api_network
    healthcheck:
      test: sh -c "rabbitmq-diagnostics -q ping"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s



networks:
  api_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
