"""create tables

Revision ID: 54e8e9e711d3
Revises: 
Create Date: 2024-02-24 12:46:37.004561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54e8e9e711d3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_table",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=125), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_menu_table_title"), "menu_table", ["title"], unique=False
    )
    op.create_table(
        "submenu_table",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=125), nullable=False),
        sa.Column("menu_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_id"], ["menu_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submenu_table_title"), "submenu_table", ["title"], unique=False
    )
    op.create_table(
        "dish_table",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=125), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("submenu_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submenu_id"], ["submenu_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dish_table_title"), "dish_table", ["title"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dish_table_title"), table_name="dish_table")
    op.drop_table("dish_table")
    op.drop_index(op.f("ix_submenu_table_title"), table_name="submenu_table")
    op.drop_table("submenu_table")
    op.drop_index(op.f("ix_menu_table_title"), table_name="menu_table")
    op.drop_table("menu_table")
    # ### end Alembic commands ###
