"""Add columns is_confirmed, confirmetion_token to user model 

Revision ID: 2958cf9923c0
Revises: 87c4515e601d
Create Date: 2024-03-03 13:37:37.862583

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2958cf9923c0"
down_revision: Union[str, None] = "87c4515e601d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_table",
        "email",
        existing_type=sa.VARCHAR(length=120),
        nullable=False,
    )
    op.alter_column(
        "user_table",
        "confirmation_token",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_table",
        "confirmation_token",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "user_table",
        "email",
        existing_type=sa.VARCHAR(length=120),
        nullable=True,
    )
    # ### end Alembic commands ###
