"""add columns confirmation_token, is_confirmed

Revision ID: 87c4515e601d
Revises: aeac03339c59
Create Date: 2024-03-03 00:06:03.238269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87c4515e601d"
down_revision: Union[str, None] = "aeac03339c59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_table",
        sa.Column("confirmation_token", sa.String(), nullable=True),
    )
    op.add_column(
        "user_table", sa.Column("is_confirmed", sa.Boolean(), nullable=False)
    )
    op.create_unique_constraint(None, "user_table", ["confirmation_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_table", type_="unique")
    op.drop_column("user_table", "is_confirmed")
    op.drop_column("user_table", "confirmation_token")
    # ### end Alembic commands ###
